namespace PSW.GMS.Common.Enums
{
    public enum ActivityEnum
    {
        DOCUMENT_REQUEST_CREATED = 12,
        DOCUMENT_FEE_PAID = 13,
        CHANNEL_ASSIGNED = 14,
        ADDITIONAL_DOCUMENTS_REQUESTED = 15,
        ADDITIONAL_DOCUMENTS_SUBMITTED = 16,
        INSPECTION_REQUESTED = 17,
        GROUNDING_REQUEST_SENT_TO_WEBOC = 18,
        GROUNDING_LOCATION_RECEIVED_FROM_WEBOC = 19,
        CONTAINERS_ALREADY_GROUNDED = 20,
        INSPECTION_REPORT_SUBMITTED = 21,
        FUMIGATION_REQUESTED = 22,
        FUMIGATION_REPORT_SUBMITTED = 23,
        DOCUMENT_APPROVED = 24,
        DOCUMENT_PROVISIONALLY_APPROVED = 25,
        DOCUMENT_REJECTED = 26,
        DOCUMENT_CANCELLED = 27,
        DOCUMENT_APPROVED_AFTER_REJECTION = 28,
        LAB_REQUESTED = 29,
        LAB_COMPLETED = 30,
        USER_ASSIGNED = 31,
        USER_UNASSIGNED = 32,
        AMENDMENT_REQUESTED = 33,
        AMENDMENT_FEE_PAID = 34,
        AMENDMENT_REQUEST_APPROVED = 35,
        AMENDMENT_REQUEST_REJECTED = 36,
        LAB_FEE_PAID = 37
    }
}