namespace PSW.GMS.common.Enums
{
    public enum InboxRequestType
    {
        IPAPPROVE = 1,
        IPREJECT = 2,
        ECAPPROVE = 3,
        ECREJECT = 4,
        IP_DOCUMENT_CALLED = 5,
        EC_DOCUMENT_CALLED = 6,
        EC_FUMIGATION_REQUESTED = 7,
        IP_CANCEL_CALL_DOCUMENT = 8,
        EC_CANCEL_CALL_DOCUMENT = 9,
        IP_CALL_DOCUMENT_ALERT = 10,
        EC_CALL_DOCUMENT_ALERT = 11,

        RO_CALL_DOCUMENT_ALERT = 22,
        RO_DOCUMENT_CALLED = 21,
        RO_FUMIGATION_REQUESTED = 24,
        ROAPPROVE = 19,
        ROREJECT = 20,
        RO_CANCEL_CALL_DOCUMENT = 23,
        IMOPRT_CONDITION_ATTACHED_TO_IP = 18,
        EC_AMENDMENT_REQUEST_CREATED_ALERT = 15,
        EC_AMENDMENT_REQUEST_APPROVED_ALERT = 16,
        EC_AMENDMENT_REQUEST_REJECTED_ALERT = 17,
        IP_REVOKE = 26,
        IP_RESTORE = 27,
        RELEASE_ORDER_CALL_LAB_ALERT = 25,
        RELEASE_ORDER_CERTIFICATE_ISSUED = 28,
        IP_AMENDMENT_APPROVE = 31,
        IP_AMENDMENT_REJECT = 32,
        IP_AMENDMENT_DOCUMENT_CALLED = 33,
        IP_AMENDMENT_DOCUMENT_SUBMITTED = 34,
        ECAPPROVEAFTERREJECT = 45,
        EC_EXTENSION_APPROVED = 52,
        EC_EXTENSION_REJECTED = 53,
        // IP_CANCEL_CALL_DOCUMENT = 8,
        EC_DOCUMENT_ASSIGNMENT = 55,
        RO_DOCUMENT_ASSIGNMENT = 56,
        IP_DOCUMENT_ASSIGNMENT = 54,
        SE_DOCUMENT_ASSIGNMENT = 57,
        EC_REVERT_CALL_DOCUMENT = 67,
        RO_REVERT_CALL_DOCUMENT = 68,
        IP_REVERT_CALL_DOCUMENT = 66,
        SE_REVERT_CALL_DOCUMENT = 69,
        IP_DOCUMENT_CALLED_UPLOADED = 62,
        // IP_AMENDMENT_DOCUMENT_CALLED_UPLOADED = 62,
        RO_DOCUMENT_CALLED_UPLOADED = 64,
        EC_DOCUMENT_CALLED_UPLOADED = 63,
        SE_DOCUMENT_CALLED_UPLOADED = 65,
        // RO_DOCUMENT_CALLED_UPLOADED_FOR_IO = 64,
        // EC_DOCUMENT_CALLED_UPLOADED_FOR_IO = 63,
        EC_FUMIGATION_REPORT_SUBMITTED = 75,
        RO_FUMIGATION_REPORT_SUBMITTED = 76,
        RO_INSPECTION_DOCUMENTS_SUBMITTED = 77,
        EC_INSPECTION_DOCUMENTS_SUBMITTED = 78,
        RO_EXAMINATION_ARRANGEMENT_MADE = 83,
        #region Seed Enlistment Inbox Request Type
        SE_ITEM_APPROVE = 35,
        SE_ITEM_REJECT = 36,
        SE_DOCUMENT_CALLED = 37,
        SE_CALL_DOC_ALERT = 38,
        SE_CALL_DOC_CANCELLED = 39,
        SE_COMPLETED = 42,
        PRO_ISSUED = 50,
        SE_SUSPENDED = 40,
        SE_RESTORE = 41,

        IMPORT_PERMIT_QUOTA_DEBITING = 84,
        IMPORT_PERMIT_QUOTA_CREDITING = 86,
        APM_APPROVED = 94,
        APM_RJECTED = 95,
        APM_DOCUMENT_CALLED = 96,

        #endregion
        #region Premises Registration Inbox Request Type
        PREMISE_REGISTRATION_SUBMITTED = 124,
        PRM_DOCUMENT_ASSIGNMENT = 97,

        PRM_DOCUMENT_ACTIVATED_DEACTIVATED = 98,
        PRM_DOCUMENT_CALLED_CANCELLED = 101,
        PRM_DOCUMENT_CALLED_REVERTED = 102,
        PRM_DOCUMENT_CALLED_SUBMITTED = 103,
        PRM_AMENDMENT_SUBMITTED_WITHOUT_PAYMENT = 104,
        PRM_AMENDMENT_SUBMITTED_WITH_PAYMENT = 105,
        CATCH_CERTIFICATE_SUBMITTED = 125,
        CC_APPROVED = 127,
        GENERIC_DOCUMENT_STATUS_NOTIFICATION = 128,
        GENERIC_CALL_DOCUMENT_STATUS_NOTIFICATION = 129,

        #endregion

        #region Product Registration Inbox Request Type
        PRODUCT_REGISTRATION = 115,
        PRR_DOCUMENT_ASSIGNMENT = 117,
        PRR_DOCUMENT_CALLED = 116,
        PRD_DOCUMENT_ACTIVATED_DEACTIVATED = 98,
        PRR_DOCUMENT_CALLED_CANCELLED = 121,
        PRR_DOCUMENT_CALLED_REVERTED = 118,
        PRR_DOCUMENT_CALLED_SUBMITTED = 119,
        PRR_CALL_DOC_ALERT = 120,

        #endregion

        #region Container Examination
        RO_CONTAINER_EXAMINATION = 99,
        EC_CONTAINER_EXAMINATION = 100,
        EXP_APPROVE = 106,
        EXP_REJECT = 107,
        EXP_DOCUMENT_CALLED = 108,
        EXP_DOCUMENT_ASSIGNMENT = 109,
        EXP_DOCUMENT_CALLED_SUBMITTED = 110,
        EXP_DOCUMENT_CALLED_BY_OFFICER = 111,
        EXP_CALL_DOC_CANCELLED = 112,
        EXP_REVOKE = 130,
        EXP_ACTIVE = 131,
        EXP_SUSPEND = 132,


        #endregion
    }
}
